version: "3.7"
services:
  anethum-webapp:
    container_name: anethum-webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./webapp:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
    depends_on: 
      - anethum-api
  anethum-api:
    container_name: anethum-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8881:8881"
    volumes:
      - "./api:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
    depends_on:
      - anethum-db
  anethum-db:
    container_name: anethum-db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=anethum
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
volumes:
  pgdata: